# Generated by Django 3.0.2 on 2020-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo de barras')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del producto')),
                ('precioVenta', models.FloatField(blank=True, null=True, verbose_name='Precio de venta del producto')),
                ('precioCompra', models.FloatField(blank=True, null=True, verbose_name='Precio de compra del producto')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Cantidad disponible')),
                ('pesaje', models.FloatField(blank=True, null=True, verbose_name='Pesaje del producto')),
                ('tipoProducto', models.IntegerField()),
            ],
        ),
    ]
