# Generated by Django 3.0.2 on 2020-01-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_prod', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo de barra del producto')),
                ('descripcio', models.CharField(max_length=100, verbose_name='Descripcion del producto')),
                ('precio', models.FloatField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
