# Generated by Django 3.0.2 on 2020-02-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GastosFijos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoGastos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de gasto')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle del pago')),
                ('fechaPago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Monto del pago')),
            ],
        ),
    ]
