# Generated by Django 3.0.2 on 2020-02-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCompra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Compra')),
                ('fechaCompra', models.DateField(blank=True, null=True, verbose_name='Fecha de la compra')),
                ('valorCompra', models.IntegerField(blank=True, null=True, verbose_name='Monto de la compra')),
            ],
        ),
    ]
